import { useState, type FormEvent } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { adminApi, clearAdminToken } from '../auth/adminSession';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Glyph, type GlyphName } from '../components/art/glyphs';
import { formatMinor } from '../utils/money';
import { DeferredMarketLinkScene } from '../components/visuals/DeferredMarketLinkScene';

interface AdminOverview {
  metrics: { total_farmers:number;total_customers:number;total_markets:number;total_orders:number;accounts:number;pending_farmers:number;orders_today:number;active_products:number };
  pending_farmers: { id: string; stall_name: string; contact_person: string | null; description: string | null; created_at: string; full_name: string }[];
  recent_products: { id: string; name: string; is_active: boolean; price_minor: number; stall_name: string; category: string }[];
}
interface ModerationReview { id: string; rating: number; title: string | null; body: string | null; status: 'visible' | 'removed'; customer_name: string; stall_name: string; product_name: string }
interface AdminMarket { id: string; name: string; address: string; city: string; state: string; country: string; currency: string; timezone: string; lat: number; lng: number; operating_days: string[]; opens_at: string; closes_at: string; image_url: string | null; is_active: boolean }
interface AdminAccount { id: string; full_name: string; phone: string; role: string; is_active: boolean; created_at: string; stall_name: string | null }
interface AdminCategory { id:string; name:string; slug:string; icon_key:string; sort_order:number }
interface AdminFarmer { id:string;stall_name:string;status:'pending'|'approved'|'suspended';currency:string;operating_days:string[];full_name:string }
interface RosterRow { farmer_id:string;stall_name:string;status:string;currency:string;stall_ref:string|null;days:string[] }
interface AdminReport { orders_by_status:{status:string;orders:number;pickup_total_minor:number|null;currency:string}[]; by_market:{id:string;name:string;city:string;currency:string;order_count:number;pickup_total_minor:number}[]; top_products:{name:string;quantity:number;orders:number;pickup_total_minor:number;currency:string}[];top_farmers:{id:string;stall_name:string;currency:string;completed_orders:number;pickup_total_minor:number}[] }
const days = ['mon','tue','wed','thu','fri','sat','sun'];
type MarketFields = Omit<AdminMarket, 'id'>;
function MarketEditor({ value, onSave }: { value?: AdminMarket; onSave: (data: MarketFields) => Promise<void> }) {
  const [form, setForm] = useState<MarketFields>(value ? { name:value.name,address:value.address,city:value.city,state:value.state,country:value.country,currency:value.currency,timezone:value.timezone,lat:value.lat,lng:value.lng,operating_days:value.operating_days,opens_at:value.opens_at.slice(0,5),closes_at:value.closes_at.slice(0,5),image_url:value.image_url,is_active:value.is_active } : { name:'',address:'',city:'Lagos',state:'Lagos',country:'Nigeria',currency:'NGN',timezone:'Africa/Lagos',lat:6.5244,lng:3.3792,operating_days:['mon','tue','wed','thu','fri','sat'],opens_at:'08:00',closes_at:'18:00',image_url:null,is_active:true });
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(e: FormEvent) { e.preventDefault();setBusy(true);setError('');try{await onSave(form);}catch(err){setError(err instanceof Error?err.message:'Could not save market.');}finally{setBusy(false);} }
  return <form onSubmit={(e)=>void submit(e)} className="grid gap-3 sm:grid-cols-2">
    {([['name','Market name'],['address','Address'],['city','City'],['state','State / region'],['country','Country'],['currency','Currency code'],['timezone','Timezone'],['lat','Latitude'],['lng','Longitude'],['image','Market photo URL']] as const).map(([key,label])=><label key={key} className="text-xs text-muted">{label}<input required={key!=='image'} value={key==='image'?(form.image_url??''):String(form[key as keyof MarketFields])} type={key==='lat'||key==='lng'?'number':key==='image'?'url':'text'} step={key==='lat'||key==='lng'?'any':undefined} onChange={(e)=>setForm({...form,...(key==='lat'||key==='lng'?{[key]:Number(e.target.value)}:key==='image'?{image_url:e.target.value||null}:{[key]:e.target.value})})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary" /></label>)}
    <label className="text-xs text-muted">Opens<input required type="time" value={form.opens_at} onChange={(e)=>setForm({...form,opens_at:e.target.value})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-primary" /></label><label className="text-xs text-muted">Closes<input required type="time" value={form.closes_at} onChange={(e)=>setForm({...form,closes_at:e.target.value})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-primary" /></label>
    <fieldset className="sm:col-span-2"><legend className="text-xs text-muted">Operating days</legend><div className="mt-2 flex flex-wrap gap-3">{days.map(d=><label key={d} className="flex items-center gap-1 text-xs capitalize"><input type="checkbox" checked={form.operating_days.includes(d)} onChange={(e)=>setForm({...form,operating_days:e.target.checked?[...form.operating_days,d]:form.operating_days.filter(x=>x!==d)})}/>{d}</label>)}</div></fieldset>
    <label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.is_active} onChange={(e)=>setForm({...form,is_active:e.target.checked})}/>Market visible to shoppers</label>
    {error?<p role="alert" className="text-sm text-danger sm:col-span-2">{error}</p>:null}<Button type="submit" loading={busy}>{busy?'Saving…':value?'Save market':'Create market'}</Button>
  </form>;
}
function CategoryEditor({ value, onSave }: { value?:AdminCategory; onSave:(data:Omit<AdminCategory,'id'>)=>Promise<void> }) {
 const [form,setForm]=useState({name:value?.name??'',slug:value?.slug??'',icon_key:value?.icon_key??'leaf',sort_order:value?.sort_order??0});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(form);}catch(err){setError(err instanceof Error?err.message:'Could not save category.');}finally{setBusy(false);}}
 return <form onSubmit={(e)=>void save(e)} className="grid gap-2 sm:grid-cols-4"><input aria-label="Category name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><input aria-label="Category slug" required pattern="[a-z][a-z0-9-]*" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="slug" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><input aria-label="Category icon key" required value={form.icon_key} onChange={e=>setForm({...form,icon_key:e.target.value})} placeholder="icon key" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><div className="flex gap-2"><input aria-label="Sort order" type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} className="h-9 w-20 rounded-lg border border-line bg-elevated px-3 text-sm"/><Button size="sm" type="submit" loading={busy}>{value?'Save':'Add'}</Button></div>{error?<p role="alert" className="text-xs text-danger sm:col-span-4">{error}</p>:null}</form>;
}
function MarketRoster({market,farmers}:{market:AdminMarket;farmers:AdminFarmer[]}){
 const cache=useQueryClient();const [farmerId,setFarmerId]=useState('');const [stallRef,setStallRef]=useState('');const [selectedDays,setSelectedDays]=useState<string[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const roster=useQuery({queryKey:['admin-market-roster',market.id],queryFn:()=>adminApi.get<RosterRow[]>(`/admin/markets/${market.id}/farmers`)});
 const selected= farmers.find(f=>f.id===farmerId);const commonDays=market.operating_days.filter(d=>selected?.operating_days.includes(d));
 function chooseFarmer(id:string){setFarmerId(id);const farmer=farmers.find(f=>f.id===id);setSelectedDays(market.operating_days.filter(d=>farmer?.operating_days.includes(d)));setStallRef(roster.data?.find(r=>r.farmer_id===id)?.stall_ref??'');}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await adminApi.put(`/admin/markets/${market.id}/farmers`,{farmer_id:farmerId,stall_ref:stallRef.trim()||null,days:selectedDays});await cache.invalidateQueries({queryKey:['admin-market-roster',market.id]});await cache.invalidateQueries({queryKey:['markets']});}catch(err){setError(err instanceof Error?err.message:'Could not update this market roster.');}finally{setBusy(false);}}
 async function remove(farmer:string){try{await adminApi.delete(`/admin/markets/${market.id}/farmers/${farmer}`);await cache.invalidateQueries({queryKey:['admin-market-roster',market.id]});await cache.invalidateQueries({queryKey:['markets']});}catch(err){setError(err instanceof Error?err.message:'Could not remove this farmer.');}}
 return <div className="mt-5 border-t border-line pt-4"><h3 className="font-semibold">Farmer roster</h3>{roster.error?<p role="alert" className="mt-2 text-sm text-danger">Could not load the market roster.</p>:null}<div className="mt-3 space-y-2">{roster.data?.map(row=><Card key={row.farmer_id} className="flex flex-wrap items-center justify-between gap-2 p-3"><div><p className="font-medium">{row.stall_name} <span className="text-xs text-muted">({row.status})</span></p><p className="text-xs text-muted">{row.stall_ref?`Stall ${row.stall_ref} · `:''}{row.days.join(', ')} · {row.currency}</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>{chooseFarmer(row.farmer_id);setSelectedDays(row.days);}}>Edit</Button><Button size="sm" variant="danger" onClick={()=>void remove(row.farmer_id)}>Remove</Button></div></Card>)}{!roster.isPending&&!roster.data?.length?<p className="text-sm text-muted">No farmers assigned yet.</p>:null}</div>
 <form onSubmit={(e)=>void save(e)} className="mt-4 grid gap-3 sm:grid-cols-[1fr_10rem]"><label className="text-xs text-muted">Farmer<select required value={farmerId} onChange={e=>chooseFarmer(e.target.value)} className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"><option value="">Choose a farmer</option>{farmers.map(f=><option key={f.id} value={f.id} disabled={f.currency!==market.currency}>{f.stall_name} · {f.status} · {f.currency}</option>)}</select></label><label className="text-xs text-muted">Stall reference<input value={stallRef} maxLength={40} onChange={e=>setStallRef(e.target.value)} placeholder="e.g. A12" className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"/></label><fieldset className="sm:col-span-2"><legend className="text-xs text-muted">Trading days</legend><div className="mt-2 flex flex-wrap gap-3">{commonDays.map(day=><label key={day} className="flex items-center gap-1 text-xs capitalize"><input type="checkbox" checked={selectedDays.includes(day)} onChange={e=>setSelectedDays(e.target.checked?[...selectedDays,day]:selectedDays.filter(d=>d!==day))}/>{day}</label>)}</div>{farmerId&&!commonDays.length?<p className="mt-1 text-xs text-danger">This farmer has no operating days in common with this market.</p>:null}</fieldset>{error?<p role="alert" className="text-sm text-danger sm:col-span-2">{error}</p>:null}<Button type="submit" size="sm" loading={busy} disabled={!farmerId||!selectedDays.length}>{busy?'Saving…':'Save roster assignment'}</Button></form></div>;
}
function Dashboard() {
  const navigate = useNavigate();
  const [mobileNavOpen,setMobileNavOpen]=useState(false);
  const [accountSearch,setAccountSearch]=useState(''); const [productSearch,setProductSearch]=useState(''); const [searchOpen,setSearchOpen]=useState(false); const [announcement,setAnnouncement]=useState({title:'',body:''}); const [announcementMessage,setAnnouncementMessage]=useState('');
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: () => adminApi.get<AdminOverview>('/admin/overview') });
  const reviews = useQuery({ queryKey: ['admin-reviews'], queryFn: () => adminApi.get<ModerationReview[]>('/admin/reviews') });
  const markets = useQuery({ queryKey:['admin-markets'],queryFn:()=>adminApi.get<AdminMarket[]>('/admin/markets') });
  const rosterFarmers = useQuery({queryKey:['admin-farmers'],queryFn:()=>adminApi.get<AdminFarmer[]>('/admin/farmers')});
  const accounts = useQuery({ queryKey:['admin-accounts',accountSearch],queryFn:()=>adminApi.get<AdminAccount[]>(`/admin/accounts?q=${encodeURIComponent(accountSearch)}`) });
  const categories = useQuery({queryKey:['admin-categories'],queryFn:()=>adminApi.get<AdminCategory[]>('/admin/categories')});
  const reports = useQuery({queryKey:['admin-reports'],queryFn:()=>adminApi.get<AdminReport>('/admin/reports')});
  async function farmerStatus(id: string, status: 'approved' | 'suspended') {
    await adminApi.patch(`/admin/farmers/${id}/status`, { status }); await overview.refetch();
  }
  async function productState(id: string, is_active: boolean) {
    await adminApi.patch(`/admin/products/${id}`, { is_active }); await overview.refetch();
  }
  async function reviewState(id: string, status: 'visible' | 'removed') { await adminApi.patch(`/admin/reviews/${id}/status`, { status }); await reviews.refetch(); }
  async function saveMarket(value:MarketFields,id?:string){ if(id) await adminApi.patch(`/admin/markets/${id}`,value); else await adminApi.post('/admin/markets',value); await markets.refetch(); }
  async function saveCategory(value:Omit<AdminCategory,'id'>,id?:string){if(id)await adminApi.patch(`/admin/categories/${id}`,value);else await adminApi.post('/admin/categories',value);await categories.refetch();}
  async function accountState(id:string,is_active:boolean){await adminApi.patch(`/admin/accounts/${id}/active`,{is_active});await accounts.refetch();}
  async function sendAnnouncement(e:FormEvent){e.preventDefault();const result=await adminApi.post<{delivered:number}>('/admin/announcements',announcement);setAnnouncementMessage(`Announcement sent to ${result.delivered} active accounts.`);setAnnouncement({title:'',body:''});}
  function signOut(){clearAdminToken();navigate('/admin/signin',{replace:true});}
  const pendingReviews = reviews.data?.filter((review) => review.status === 'visible').length ?? 0;
  const matchingProducts = (overview.data?.recent_products ?? []).filter((product) => {
    const query = productSearch.trim().toLocaleLowerCase();
    return !query || `${product.name} ${product.category} ${product.stall_name}`.toLocaleLowerCase().includes(query);
  });
  const searchTerm = accountSearch.trim().toLocaleLowerCase();
  const globalSearchResults: { label: string; detail: string; icon: GlyphName; href: string; productQuery?: string }[] = searchTerm ? [
    ...(accounts.data ?? []).filter((account) => `${account.full_name} ${account.role} ${account.phone} ${account.stall_name ?? ''}`.toLocaleLowerCase().includes(searchTerm)).slice(0, 3).map((account) => ({ label: account.full_name, detail: `${account.role} · ${account.phone}`, icon: 'people' as const, href: '#account-management' })),
    ...(overview.data?.recent_products ?? []).filter((product) => `${product.name} ${product.category} ${product.stall_name}`.toLocaleLowerCase().includes(searchTerm)).slice(0, 3).map((product) => ({ label: product.name, detail: `${product.category} · ${product.stall_name}`, icon: 'package' as const, href: '#product-moderation', productQuery: product.name })),
    ...(markets.data ?? []).filter((market) => `${market.name} ${market.city} ${market.state} ${market.country}`.toLocaleLowerCase().includes(searchTerm)).slice(0, 2).map((market) => ({ label: market.name, detail: `${market.city}, ${market.country}`, icon: 'stall' as const, href: '#market-management' })),
    ...(rosterFarmers.data ?? []).filter((farmer) => `${farmer.stall_name} ${farmer.full_name}`.toLocaleLowerCase().includes(searchTerm)).slice(0, 2).map((farmer) => ({ label: farmer.stall_name, detail: `${farmer.full_name} · ${farmer.status}`, icon: 'farmer' as const, href: '#farmer-applications' })),
  ].slice(0, 8) : [];
  const adminEmail = window.localStorage.getItem('marketlink.admin.email') ?? 'Platform Owner';
  const nav: { label:string; href:string; icon:GlyphName }[] = [
    { label:'Overview',href:'#overview',icon:'home' },
    { label:'Farmers',href:'#farmer-applications',icon:'farmer' },
    { label:'Buyers & sellers',href:'#account-management',icon:'people' },
    { label:'Markets',href:'#market-management',icon:'stall' },
    { label:'Products',href:'#product-moderation',icon:'package' },
    { label:'Reviews',href:'#review-moderation',icon:'star' },
    { label:'Reports',href:'#reports',icon:'list' },
    { label:'Settings',href:'#settings',icon:'settings' },
  ];
  return <div className="min-h-screen bg-[#f2f7f3] text-[#10241f] lg:flex">
    {mobileNavOpen?<button type="button" aria-label="Close admin navigation" onClick={()=>setMobileNavOpen(false)} className="fixed inset-0 z-30 bg-black/45 lg:hidden"/>:null}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[min(84vw,18rem)] shrink-0 flex-col overflow-y-auto bg-[#071b17] px-4 py-5 text-white shadow-2xl transition-transform duration-200 lg:sticky lg:top-0 lg:z-auto lg:h-screen lg:w-[236px] lg:translate-x-0 lg:shadow-none ${mobileNavOpen?'translate-x-0':'-translate-x-full'}`}>
      <Link to="/admin" className="mb-5 flex items-center gap-3 px-2 text-xl font-bold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-accent text-paper shadow-[0_4px_18px_rgba(33,106,73,0.18)]"><Glyph name="leaf" size={21} /></span>MarketLink</Link>
      <p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-200/60">Platform</p>
      <nav aria-label="Admin sections" className="flex flex-col gap-1">{nav.map(({label,href,icon},i)=><a key={href} href={href} onClick={()=>setMobileNavOpen(false)} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition hover:bg-white/10 ${i===0?'bg-emerald-800/70 text-white':'text-emerald-50/75'}`}><Glyph name={icon} size={15} className="shrink-0" />{label}</a>)}</nav>
      <div className="mt-auto rounded-2xl border border-white/10 bg-white/[.04] p-4 text-xs text-emerald-50/70"><p className="font-semibold text-white">MarketLink</p><p className="mt-1">Better markets.<br/>Stronger communities.</p><button onClick={signOut} className="mt-4 min-h-10 text-emerald-200 hover:text-white">Sign out</button></div>
    </aside>
    <div className="min-w-0 flex-1">
      <header className="sticky top-0 z-20 flex flex-wrap items-center gap-2 border-b border-[#dce8df] bg-white/90 px-3 py-2.5 backdrop-blur sm:gap-4 sm:px-4 md:px-8">
        <button type="button" aria-label={mobileNavOpen?'Close admin menu':'Open admin menu'} aria-expanded={mobileNavOpen} onClick={()=>setMobileNavOpen(!mobileNavOpen)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[#dce8df] text-xl lg:hidden">☰</button>
        <div className="relative order-3 min-w-0 basis-full flex-1 sm:order-none sm:basis-auto"><label className="relative block"><span className="sr-only">Search farmers, products, markets, and users</span><span aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#789087]">⌕</span><input value={accountSearch} onFocus={()=>setSearchOpen(true)} onChange={(e)=>{setAccountSearch(e.target.value);setSearchOpen(true);}} onKeyDown={(e)=>{if(e.key==='Escape')setSearchOpen(false);}} placeholder="Search farmers, products, markets, users…" className="h-11 w-full max-w-2xl rounded-full border border-transparent bg-[#eff5f1] pl-11 pr-4 text-sm outline-none transition focus:border-emerald-700/30 focus:bg-white" /></label>{searchOpen&&searchTerm?<div className="absolute left-0 right-0 top-[calc(100%+8px)] z-50 max-h-[min(70vh,26rem)] max-w-2xl overflow-y-auto rounded-2xl border border-[#dce8df] bg-white p-2 shadow-xl">{globalSearchResults.map((result,index)=><a key={`${result.href}:${result.label}:${index}`} href={result.href} onMouseDown={(e)=>e.preventDefault()} onClick={()=>{if(result.productQuery)setProductSearch(result.productQuery);setSearchOpen(false);}} className="flex min-h-12 items-center gap-3 rounded-xl px-3 py-2 hover:bg-[#eff5f1] focus:bg-[#eff5f1]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-800"><Glyph name={result.icon} size={16}/></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-[#10241f]">{result.label}</span><span className="block truncate text-xs text-[#71867d]">{result.detail}</span></span></a>)}{!globalSearchResults.length?<p className="px-3 py-4 text-sm text-[#71867d]">No recent matches for “{accountSearch.trim()}”.</p>:null}</div>:null}</div>
        <a href="#review-moderation" aria-label={`${pendingReviews} reviews to review`} className="relative grid h-10 w-10 shrink-0 place-items-center rounded-full text-xl hover:bg-[#eff5f1]">♧{pendingReviews>0?<span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-red-600 px-1 text-[10px] font-bold text-white">{pendingReviews}</span>:null}</a>
        <Link to="/admin" className="flex shrink-0 items-center gap-2 rounded-full px-2 py-1 hover:bg-[#eff5f1]"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-900">A</span><span className="hidden text-left sm:block"><span className="block text-sm font-semibold">Admin</span><span className="block max-w-40 truncate text-xs text-[#6d8179]">{adminEmail}</span></span><span className="hidden text-xs sm:inline">⌄</span></Link>
      </header>
      <main id="overview" className="mx-auto min-w-0 max-w-[1800px] px-4 py-4 md:px-6 md:py-5">
        <div className="relative mb-4 flex flex-wrap items-end justify-between gap-3"><DeferredMarketLinkScene kind="admin" className="pointer-events-none absolute right-0 top-0 z-0 h-28 w-36 opacity-35 sm:h-36 sm:w-56 lg:h-44 lg:w-72" /><div className="relative z-10"><p className="text-sm font-medium text-emerald-800">Good afternoon, Admin <span aria-hidden="true">👋</span></p><h1 className="mt-1 text-3xl font-bold tracking-tight md:text-4xl">Platform Overview</h1><p className="mt-1.5 max-w-2xl text-sm text-[#687d74]">Monitor activity, manage users and markets, and keep the MarketLink ecosystem running smoothly.</p></div><p className="relative z-10 rounded-xl border border-[#dce8df] bg-white px-3 py-1.5 text-sm text-[#53685f]">{new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date())}</p></div>
    {overview.isPending ? <p className="mt-4 text-muted">Loading operations…</p> : null}{overview.error ? <Card className="mt-4 p-4 text-danger">{overview.error instanceof Error ? overview.error.message : 'Could not load admin data.'}</Card> : null}
    {overview.data ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Total users', overview.data.metrics.accounts, '♧', 'All registered accounts'], ['Farmers', overview.data.metrics.total_farmers, '♙', `${overview.data.metrics.pending_farmers} awaiting approval`], ['Buyers', overview.data.metrics.total_customers, '🛒', `${overview.data.metrics.orders_today} orders today`], ['Active markets', overview.data.metrics.total_markets, '▣', `${overview.data.metrics.active_products} active products`]].map(([label, value, icon, note]) => <Card key={label} className="rounded-2xl border-[#e2ece5] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-xl text-emerald-800">{label === 'Farmers' ? <Glyph name="farmer" size={22} /> : label === 'Total users' ? <Glyph name="people" size={22} /> : icon}</span><span className="text-[11px] font-medium text-[#71867d]">Live total</span></div><p className="mt-3 text-sm font-medium text-[#53685f]">{label}</p><p className="mt-0.5 text-3xl font-bold tracking-tight">{value}</p><p className="mt-0.5 text-xs text-[#71867d]">{note}</p></Card>)}</div>
      <section id="farmer-applications" className="mt-4 h-fit scroll-mt-20 rounded-2xl border border-[#dce8df] bg-white p-3 shadow-sm"><h2 className="font-display text-xl font-bold">Farmer applications</h2><div className="mt-2 space-y-2">{overview.data.pending_farmers.map((farmer) => <Card key={farmer.id} className="p-3"><h3 className="font-semibold">{farmer.stall_name}</h3><p className="text-sm text-muted">{farmer.full_name}{farmer.contact_person ? ` · ${farmer.contact_person}` : ''}</p>{farmer.description ? <p className="mt-1.5 text-sm text-muted">{farmer.description}</p> : null}<div className="mt-3 flex gap-2"><Button size="sm" onClick={() => void farmerStatus(farmer.id, 'approved')}>Approve stall</Button><Button size="sm" variant="danger" onClick={() => void farmerStatus(farmer.id, 'suspended')}>Suspend</Button></div></Card>)}{!overview.data.pending_farmers.length ? <Card className="p-3 text-sm text-muted">No pending applications.</Card> : null}</div></section>
      <section id="product-moderation" className="mt-4 min-w-0 scroll-mt-20 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-xl font-bold">Product moderation</h2><label className="relative min-w-0 flex-1 sm:max-w-sm"><span className="sr-only">Search products</span><span aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted">⌕</span><input value={productSearch} onChange={(e)=>setProductSearch(e.target.value)} placeholder="Search products, categories, farmers…" className="h-10 w-full rounded-xl border border-line bg-elevated pl-9 pr-3 text-sm text-primary outline-none focus:border-accent/40" /></label></div><div className="mt-3 overflow-x-auto"><div className="flex w-max min-w-full gap-2">{matchingProducts.map((product) => <Card key={product.id} className="grid w-[min(23rem,82vw)] shrink-0 grid-cols-[minmax(7rem,1fr)_minmax(7rem,1fr)_auto] items-center gap-3 p-2.5"><p className="truncate font-medium">{product.name}</p><p className="truncate text-xs text-muted">{product.category} · {product.stall_name}</p><Button size="sm" variant={product.is_active ? 'danger' : 'ghost'} onClick={() => void productState(product.id, !product.is_active)}>{product.is_active ? 'Hide' : 'Restore'}</Button></Card>)}</div>{!matchingProducts.length?<p className="mt-3 text-sm text-muted">No recent products match “{productSearch}”.</p>:null}</div></section>
      <section id="review-moderation" className="mt-4 scroll-mt-20 min-w-0 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><h2 className="font-display text-xl font-bold">Review moderation</h2>{reviews.isPending ? <p className="mt-2 text-sm text-muted">Loading reviews…</p> : null}<div className="mt-3 grid gap-2.5 md:grid-cols-2">{reviews.data?.map((review) => <Card key={review.id} className="min-w-0 p-3"><div className="flex min-w-0 justify-between gap-3"><div className="min-w-0"><p className="break-words font-semibold">{review.product_name} · {'★'.repeat(review.rating)}</p><p className="break-words text-xs text-muted">{review.customer_name} · {review.stall_name}</p></div><Button className="shrink-0" size="sm" variant={review.status === 'visible' ? 'danger' : 'ghost'} onClick={() => void reviewState(review.id, review.status === 'visible' ? 'removed' : 'visible')}>{review.status === 'visible' ? 'Hide review' : 'Restore'}</Button></div>{review.title ? <p className="mt-1.5 break-words font-medium">{review.title}</p> : null}{review.body ? <p className="mt-1 break-words text-sm text-muted">{review.body}</p> : null}</Card>)}</div>{!reviews.isPending && !reviews.data?.length ? <Card className="mt-3 p-4 text-sm text-muted">No reviews to moderate yet.</Card> : null}</section>
      <section id="market-management" className="mt-4 scroll-mt-20 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><h2 className="font-display text-xl font-bold">Market management</h2><details className="mt-3 rounded-xl border border-line bg-surface p-3"><summary className="cursor-pointer font-semibold">Add a market</summary><div className="mt-3"><MarketEditor onSave={(data)=>saveMarket(data)}/></div></details><div className="mt-2 space-y-2">{markets.data?.map((market)=><details key={market.id} className="rounded-xl border border-line bg-surface p-3"><summary className="cursor-pointer font-medium">{market.name} · {market.city}, {market.country} · {market.is_active?'Active':'Hidden'}</summary><div className="mt-3"><MarketEditor value={market} onSave={(data)=>saveMarket(data,market.id)}/><MarketRoster market={market} farmers={rosterFarmers.data??[]}/></div></details>)}</div></section>
      <section id="settings" className="mt-4 scroll-mt-20 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><h2 className="font-display text-xl font-bold">Product categories</h2><Card className="mt-3 space-y-2 p-3"><CategoryEditor onSave={(data)=>saveCategory(data)}/>{categories.data?.map(category=><div key={category.id} className="border-t border-line pt-2"><p className="mb-1 text-sm font-medium">{category.name} · {category.slug}</p><CategoryEditor value={category} onSave={(data)=>saveCategory(data,category.id)}/></div>)}</Card></section>
      <section id="reports" className="mt-4 scroll-mt-20 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><h2 className="font-display text-xl font-bold">Order & pickup reports</h2><p className="mt-1 text-sm text-muted">Sales totals include completed pickups only. Payment is handled in person.</p>{reports.isPending?<p className="mt-2 text-sm text-muted">Generating reports…</p>:null}<div className="mt-3 grid gap-3 lg:grid-cols-2"><Card className="p-3"><h3 className="font-semibold">Completed pickups by market</h3><div className="mt-2 space-y-1.5">{reports.data?.by_market.map((row)=><div key={row.id} className="flex justify-between gap-3 border-b border-line pb-1.5 text-sm"><span>{row.name} · {row.city}<span className="block text-xs text-muted">{row.order_count} completed</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card><Card className="p-3"><h3 className="font-semibold">Most picked products</h3><div className="mt-2 space-y-1.5">{reports.data?.top_products.map((row)=><div key={`${row.name}:${row.currency}`} className="flex justify-between gap-3 border-b border-line pb-1.5 text-sm"><span>{row.name}<span className="block text-xs text-muted">{row.quantity} units · {row.orders} orders</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card><Card className="p-3 lg:col-span-2"><h3 className="font-semibold">Most active farmers · completed pickups</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{reports.data?.top_farmers.map((row)=><div key={row.id} className="flex justify-between gap-3 border-b border-line pb-1.5 text-sm"><span>{row.stall_name}<span className="block text-xs text-muted">{row.completed_orders} completed orders</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card></div></section>
      <section id="account-management" className="mt-4 scroll-mt-20 grid min-w-0 gap-4 rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><div className="min-w-0"><h2 className="font-display text-xl font-bold">Account management</h2><input value={accountSearch} onChange={(e)=>setAccountSearch(e.target.value)} placeholder="Search name or phone" className="mt-2 h-10 w-full rounded-xl border border-line bg-elevated px-3 text-sm"/><div className="mt-3 overflow-x-auto"><div className="flex w-max min-w-full gap-2">{accounts.data?.map((account)=><Card key={account.id} className="grid w-[min(23rem,82vw)] shrink-0 grid-cols-[minmax(7rem,1fr)_minmax(7rem,1fr)_auto] items-center gap-3 p-2.5"><div className="min-w-0"><p className="truncate font-medium">{account.full_name}</p><p className="text-xs capitalize text-muted">{account.role}</p></div><div className="min-w-0"><p className="truncate text-sm">{account.phone}</p><p className="truncate text-xs text-muted">{account.stall_name || '—'}</p></div><Button className="shrink-0" size="sm" variant={account.is_active?'danger':'ghost'} onClick={()=>void accountState(account.id,!account.is_active)}>{account.is_active?'Disable':'Enable'}</Button></Card>)}</div></div></div><div className="min-w-0"><h2 className="font-display text-xl font-bold">Announcements</h2><Card className="mt-2 p-3"><form onSubmit={(e)=>void sendAnnouncement(e)} className="space-y-2"><label className="block text-xs text-muted">Title<input required maxLength={100} value={announcement.title} onChange={(e)=>setAnnouncement({...announcement,title:e.target.value})} className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"/></label><label className="block text-xs text-muted">Message<textarea required maxLength={1000} rows={3} value={announcement.body} onChange={(e)=>setAnnouncement({...announcement,body:e.target.value})} className="mt-1 block w-full rounded-lg border border-line bg-elevated p-3 text-sm text-primary"/></label><Button className="w-full sm:w-auto" type="submit">Send to active accounts</Button>{announcementMessage?<p role="status" className="text-sm text-accent">{announcementMessage}</p>:null}</form></Card></div></section></> : null}
      </main>
    </div>
  </div>;
}
export default function AdminDashboard() { return <Dashboard />; }
