import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { RequireAuth } from '../auth/RequireAuth';
import { useAuth } from '../auth/AuthProvider';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { formatMinor } from '../utils/money';

interface AdminOverview {
  metrics: { total_farmers:number;total_customers:number;total_markets:number;total_orders:number;accounts:number;pending_farmers:number;orders_today:number;active_products:number };
  pending_farmers: { id: string; stall_name: string; contact_person: string | null; description: string | null; created_at: string; full_name: string }[];
  recent_products: { id: string; name: string; is_active: boolean; price_minor: number; stall_name: string; category: string }[];
}
interface ModerationReview { id: string; rating: number; title: string | null; body: string | null; status: 'visible' | 'removed'; customer_name: string; stall_name: string; product_name: string }
interface AdminMarket { id: string; name: string; address: string; city: string; state: string; country: string; currency: string; timezone: string; lat: number; lng: number; operating_days: string[]; opens_at: string; closes_at: string; image_url: string | null; is_active: boolean }
interface AdminAccount { id: string; full_name: string; phone: string; role: string; is_active: boolean; created_at: string; stall_name: string | null }
interface AdminCategory { id:string; name:string; slug:string; icon_key:string; sort_order:number }
interface AdminFarmer { id:string;stall_name:string;status:'pending'|'approved'|'suspended';currency:string;operating_days:string[];full_name:string }
interface RosterRow { farmer_id:string;stall_name:string;status:string;currency:string;stall_ref:string|null;days:string[] }
interface AdminReport { orders_by_status:{status:string;orders:number;pickup_total_minor:number|null;currency:string}[]; by_market:{id:string;name:string;city:string;currency:string;order_count:number;pickup_total_minor:number}[]; top_products:{name:string;quantity:number;orders:number;pickup_total_minor:number;currency:string}[];top_farmers:{id:string;stall_name:string;currency:string;completed_orders:number;pickup_total_minor:number}[] }
const days = ['mon','tue','wed','thu','fri','sat','sun'];
type MarketFields = Omit<AdminMarket, 'id'>;
function MarketEditor({ value, onSave }: { value?: AdminMarket; onSave: (data: MarketFields) => Promise<void> }) {
  const [form, setForm] = useState<MarketFields>(value ? { name:value.name,address:value.address,city:value.city,state:value.state,country:value.country,currency:value.currency,timezone:value.timezone,lat:value.lat,lng:value.lng,operating_days:value.operating_days,opens_at:value.opens_at.slice(0,5),closes_at:value.closes_at.slice(0,5),image_url:value.image_url,is_active:value.is_active } : { name:'',address:'',city:'Lagos',state:'Lagos',country:'Nigeria',currency:'NGN',timezone:'Africa/Lagos',lat:6.5244,lng:3.3792,operating_days:['mon','tue','wed','thu','fri','sat'],opens_at:'08:00',closes_at:'18:00',image_url:null,is_active:true });
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(e: FormEvent) { e.preventDefault();setBusy(true);setError('');try{await onSave(form);}catch(err){setError(err instanceof Error?err.message:'Could not save market.');}finally{setBusy(false);} }
  return <form onSubmit={(e)=>void submit(e)} className="grid gap-3 sm:grid-cols-2">
    {([['name','Market name'],['address','Address'],['city','City'],['state','State / region'],['country','Country'],['currency','Currency code'],['timezone','Timezone'],['lat','Latitude'],['lng','Longitude'],['image','Market photo URL']] as const).map(([key,label])=><label key={key} className="text-xs text-muted">{label}<input required={key!=='image'} value={key==='image'?(form.image_url??''):String(form[key as keyof MarketFields])} type={key==='lat'||key==='lng'?'number':key==='image'?'url':'text'} step={key==='lat'||key==='lng'?'any':undefined} onChange={(e)=>setForm({...form,...(key==='lat'||key==='lng'?{[key]:Number(e.target.value)}:key==='image'?{image_url:e.target.value||null}:{[key]:e.target.value})})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary" /></label>)}
    <label className="text-xs text-muted">Opens<input required type="time" value={form.opens_at} onChange={(e)=>setForm({...form,opens_at:e.target.value})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-primary" /></label><label className="text-xs text-muted">Closes<input required type="time" value={form.closes_at} onChange={(e)=>setForm({...form,closes_at:e.target.value})} className="mt-1 block h-9 w-full rounded-lg border border-line bg-elevated px-3 text-primary" /></label>
    <fieldset className="sm:col-span-2"><legend className="text-xs text-muted">Operating days</legend><div className="mt-2 flex flex-wrap gap-3">{days.map(d=><label key={d} className="flex items-center gap-1 text-xs capitalize"><input type="checkbox" checked={form.operating_days.includes(d)} onChange={(e)=>setForm({...form,operating_days:e.target.checked?[...form.operating_days,d]:form.operating_days.filter(x=>x!==d)})}/>{d}</label>)}</div></fieldset>
    <label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={form.is_active} onChange={(e)=>setForm({...form,is_active:e.target.checked})}/>Market visible to shoppers</label>
    {error?<p role="alert" className="text-sm text-danger sm:col-span-2">{error}</p>:null}<Button type="submit" loading={busy}>{busy?'Saving…':value?'Save market':'Create market'}</Button>
  </form>;
}
function CategoryEditor({ value, onSave }: { value?:AdminCategory; onSave:(data:Omit<AdminCategory,'id'>)=>Promise<void> }) {
 const [form,setForm]=useState({name:value?.name??'',slug:value?.slug??'',icon_key:value?.icon_key??'leaf',sort_order:value?.sort_order??0});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(form);}catch(err){setError(err instanceof Error?err.message:'Could not save category.');}finally{setBusy(false);}}
 return <form onSubmit={(e)=>void save(e)} className="grid gap-2 sm:grid-cols-4"><input aria-label="Category name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><input aria-label="Category slug" required pattern="[a-z][a-z0-9-]*" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="slug" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><input aria-label="Category icon key" required value={form.icon_key} onChange={e=>setForm({...form,icon_key:e.target.value})} placeholder="icon key" className="h-9 rounded-lg border border-line bg-elevated px-3 text-sm"/><div className="flex gap-2"><input aria-label="Sort order" type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} className="h-9 w-20 rounded-lg border border-line bg-elevated px-3 text-sm"/><Button size="sm" type="submit" loading={busy}>{value?'Save':'Add'}</Button></div>{error?<p role="alert" className="text-xs text-danger sm:col-span-4">{error}</p>:null}</form>;
}
function MarketRoster({market,farmers}:{market:AdminMarket;farmers:AdminFarmer[]}){
 const {api}=useAuth();const cache=useQueryClient();const [farmerId,setFarmerId]=useState('');const [stallRef,setStallRef]=useState('');const [selectedDays,setSelectedDays]=useState<string[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const roster=useQuery({queryKey:['admin-market-roster',market.id],queryFn:()=>api.get<RosterRow[]>(`/admin/markets/${market.id}/farmers`)});
 const selected= farmers.find(f=>f.id===farmerId);const commonDays=market.operating_days.filter(d=>selected?.operating_days.includes(d));
 function chooseFarmer(id:string){setFarmerId(id);const farmer=farmers.find(f=>f.id===id);setSelectedDays(market.operating_days.filter(d=>farmer?.operating_days.includes(d)));setStallRef(roster.data?.find(r=>r.farmer_id===id)?.stall_ref??'');}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api.put(`/admin/markets/${market.id}/farmers`,{farmer_id:farmerId,stall_ref:stallRef.trim()||null,days:selectedDays});await cache.invalidateQueries({queryKey:['admin-market-roster',market.id]});await cache.invalidateQueries({queryKey:['markets']});}catch(err){setError(err instanceof Error?err.message:'Could not update this market roster.');}finally{setBusy(false);}}
 async function remove(farmer:string){try{await api.delete(`/admin/markets/${market.id}/farmers/${farmer}`);await cache.invalidateQueries({queryKey:['admin-market-roster',market.id]});await cache.invalidateQueries({queryKey:['markets']});}catch(err){setError(err instanceof Error?err.message:'Could not remove this farmer.');}}
 return <div className="mt-5 border-t border-line pt-4"><h3 className="font-semibold">Farmer roster</h3>{roster.error?<p role="alert" className="mt-2 text-sm text-danger">Could not load the market roster.</p>:null}<div className="mt-3 space-y-2">{roster.data?.map(row=><Card key={row.farmer_id} className="flex flex-wrap items-center justify-between gap-2 p-3"><div><p className="font-medium">{row.stall_name} <span className="text-xs text-muted">({row.status})</span></p><p className="text-xs text-muted">{row.stall_ref?`Stall ${row.stall_ref} · `:''}{row.days.join(', ')} · {row.currency}</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>{chooseFarmer(row.farmer_id);setSelectedDays(row.days);}}>Edit</Button><Button size="sm" variant="danger" onClick={()=>void remove(row.farmer_id)}>Remove</Button></div></Card>)}{!roster.isPending&&!roster.data?.length?<p className="text-sm text-muted">No farmers assigned yet.</p>:null}</div>
 <form onSubmit={(e)=>void save(e)} className="mt-4 grid gap-3 sm:grid-cols-[1fr_10rem]"><label className="text-xs text-muted">Farmer<select required value={farmerId} onChange={e=>chooseFarmer(e.target.value)} className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"><option value="">Choose a farmer</option>{farmers.map(f=><option key={f.id} value={f.id} disabled={f.currency!==market.currency}>{f.stall_name} · {f.status} · {f.currency}</option>)}</select></label><label className="text-xs text-muted">Stall reference<input value={stallRef} maxLength={40} onChange={e=>setStallRef(e.target.value)} placeholder="e.g. A12" className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"/></label><fieldset className="sm:col-span-2"><legend className="text-xs text-muted">Trading days</legend><div className="mt-2 flex flex-wrap gap-3">{commonDays.map(day=><label key={day} className="flex items-center gap-1 text-xs capitalize"><input type="checkbox" checked={selectedDays.includes(day)} onChange={e=>setSelectedDays(e.target.checked?[...selectedDays,day]:selectedDays.filter(d=>d!==day))}/>{day}</label>)}</div>{farmerId&&!commonDays.length?<p className="mt-1 text-xs text-danger">This farmer has no operating days in common with this market.</p>:null}</fieldset>{error?<p role="alert" className="text-sm text-danger sm:col-span-2">{error}</p>:null}<Button type="submit" size="sm" loading={busy} disabled={!farmerId||!selectedDays.length}>{busy?'Saving…':'Save roster assignment'}</Button></form></div>;
}
function Dashboard() {
  const { api } = useAuth();
  const [accountSearch,setAccountSearch]=useState(''); const [announcement,setAnnouncement]=useState({title:'',body:''}); const [announcementMessage,setAnnouncementMessage]=useState('');
  const overview = useQuery({ queryKey: ['admin-overview'], queryFn: () => api.get<AdminOverview>('/admin/overview') });
  const reviews = useQuery({ queryKey: ['admin-reviews'], queryFn: () => api.get<ModerationReview[]>('/admin/reviews') });
  const markets = useQuery({ queryKey:['admin-markets'],queryFn:()=>api.get<AdminMarket[]>('/admin/markets') });
  const rosterFarmers = useQuery({queryKey:['admin-farmers'],queryFn:()=>api.get<AdminFarmer[]>('/admin/farmers')});
  const accounts = useQuery({ queryKey:['admin-accounts',accountSearch],queryFn:()=>api.get<AdminAccount[]>(`/admin/accounts?q=${encodeURIComponent(accountSearch)}`) });
  const categories = useQuery({queryKey:['admin-categories'],queryFn:()=>api.get<AdminCategory[]>('/admin/categories')});
  const reports = useQuery({queryKey:['admin-reports'],queryFn:()=>api.get<AdminReport>('/admin/reports')});
  async function farmerStatus(id: string, status: 'approved' | 'suspended') {
    await api.patch(`/admin/farmers/${id}/status`, { status }); await overview.refetch();
  }
  async function productState(id: string, is_active: boolean) {
    await api.patch(`/admin/products/${id}`, { is_active }); await overview.refetch();
  }
  async function reviewState(id: string, status: 'visible' | 'removed') { await api.patch(`/admin/reviews/${id}/status`, { status }); await reviews.refetch(); }
  async function saveMarket(value:MarketFields,id?:string){ if(id) await api.patch(`/admin/markets/${id}`,value); else await api.post('/admin/markets',value); await markets.refetch(); }
  async function saveCategory(value:Omit<AdminCategory,'id'>,id?:string){if(id)await api.patch(`/admin/categories/${id}`,value);else await api.post('/admin/categories',value);await categories.refetch();}
  async function accountState(id:string,is_active:boolean){await api.patch(`/admin/accounts/${id}/active`,{is_active});await accounts.refetch();}
  async function sendAnnouncement(e:FormEvent){e.preventDefault();const result=await api.post<{delivered:number}>('/admin/announcements',announcement);setAnnouncementMessage(`Announcement sent to ${result.delivered} active accounts.`);setAnnouncement({title:'',body:''});}
  return <section className="mx-auto max-w-6xl px-4 py-8 md:py-12"><p className="text-sm text-accent">Market operations</p><h1 className="font-display text-3xl font-bold">Admin dashboard</h1><p className="mt-2 text-sm text-muted">Review farmer applications and moderate active listings.</p>
    {overview.isPending ? <p className="mt-6 text-muted">Loading operations…</p> : null}{overview.error ? <Card className="mt-6 p-5 text-danger">{overview.error instanceof Error ? overview.error.message : 'Could not load admin data.'}</Card> : null}
    {overview.data ? <><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Farmers', overview.data.metrics.total_farmers], ['Customers', overview.data.metrics.total_customers], ['Markets', overview.data.metrics.total_markets], ['All orders', overview.data.metrics.total_orders]].map(([label, value]) => <Card key={label} className="p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p></Card>)}</div><p className="mt-3 text-xs text-muted">{overview.data.metrics.pending_farmers} farmer applications pending · {overview.data.metrics.orders_today} orders today · {overview.data.metrics.active_products} active products · {overview.data.metrics.accounts} accounts total</p>
      <div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="font-display text-2xl font-bold">Farmer applications</h2><div className="mt-4 space-y-3">{overview.data.pending_farmers.map((farmer) => <Card key={farmer.id} className="p-4"><h3 className="font-semibold">{farmer.stall_name}</h3><p className="text-sm text-muted">{farmer.full_name}{farmer.contact_person ? ` · ${farmer.contact_person}` : ''}</p>{farmer.description ? <p className="mt-2 text-sm text-muted">{farmer.description}</p> : null}<div className="mt-4 flex gap-2"><Button size="sm" onClick={() => void farmerStatus(farmer.id, 'approved')}>Approve stall</Button><Button size="sm" variant="danger" onClick={() => void farmerStatus(farmer.id, 'suspended')}>Suspend</Button></div></Card>)}{!overview.data.pending_farmers.length ? <Card className="p-5 text-sm text-muted">No pending applications.</Card> : null}</div></section>
      <section><h2 className="font-display text-2xl font-bold">Product moderation</h2><div className="mt-4 space-y-2">{overview.data.recent_products.map((product) => <Card key={product.id} className="flex items-center justify-between gap-3 p-3"><div className="min-w-0"><p className="truncate font-medium">{product.name}</p><p className="text-xs text-muted">{product.category} · {product.stall_name}</p></div><Button size="sm" variant={product.is_active ? 'danger' : 'ghost'} onClick={() => void productState(product.id, !product.is_active)}>{product.is_active ? 'Hide' : 'Restore'}</Button></Card>)}</div></section></div>
      <section className="mt-8"><h2 className="font-display text-2xl font-bold">Review moderation</h2>{reviews.isPending ? <p className="mt-3 text-sm text-muted">Loading reviews…</p> : null}<div className="mt-4 grid gap-3 md:grid-cols-2">{reviews.data?.map((review) => <Card key={review.id} className="p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{review.product_name} · {'★'.repeat(review.rating)}</p><p className="text-xs text-muted">{review.customer_name} · {review.stall_name}</p></div><Button size="sm" variant={review.status === 'visible' ? 'danger' : 'ghost'} onClick={() => void reviewState(review.id, review.status === 'visible' ? 'removed' : 'visible')}>{review.status === 'visible' ? 'Hide review' : 'Restore'}</Button></div>{review.title ? <p className="mt-2 font-medium">{review.title}</p> : null}{review.body ? <p className="mt-1 text-sm text-muted">{review.body}</p> : null}</Card>)}</div>{!reviews.isPending && !reviews.data?.length ? <Card className="mt-4 p-5 text-sm text-muted">No reviews to moderate yet.</Card> : null}</section>
      <section className="mt-8"><h2 className="font-display text-2xl font-bold">Market management</h2><details className="mt-4 rounded-xl border border-line bg-surface p-4"><summary className="cursor-pointer font-semibold">Add a market</summary><div className="mt-4"><MarketEditor onSave={(data)=>saveMarket(data)}/></div></details><div className="mt-3 space-y-2">{markets.data?.map((market)=><details key={market.id} className="rounded-xl border border-line bg-surface p-4"><summary className="cursor-pointer font-medium">{market.name} · {market.city}, {market.country} · {market.is_active?'Active':'Hidden'}</summary><div className="mt-4"><MarketEditor value={market} onSave={(data)=>saveMarket(data,market.id)}/><MarketRoster market={market} farmers={rosterFarmers.data??[]}/></div></details>)}</div></section>
      <section className="mt-8"><h2 className="font-display text-2xl font-bold">Product categories</h2><Card className="mt-4 space-y-3 p-4"><CategoryEditor onSave={(data)=>saveCategory(data)}/>{categories.data?.map(category=><div key={category.id} className="border-t border-line pt-3"><p className="mb-2 text-sm font-medium">{category.name} · {category.slug}</p><CategoryEditor value={category} onSave={(data)=>saveCategory(data,category.id)}/></div>)}</Card></section>
      <section className="mt-8"><h2 className="font-display text-2xl font-bold">Order & pickup reports</h2><p className="mt-1 text-sm text-muted">Sales totals include completed pickups only. Payment is handled in person.</p>{reports.isPending?<p className="mt-3 text-sm text-muted">Generating reports…</p>:null}<div className="mt-4 grid gap-4 lg:grid-cols-2"><Card className="p-4"><h3 className="font-semibold">Completed pickups by market</h3><div className="mt-3 space-y-2">{reports.data?.by_market.map((row)=><div key={row.id} className="flex justify-between gap-3 border-b border-line pb-2 text-sm"><span>{row.name} · {row.city}<span className="block text-xs text-muted">{row.order_count} completed</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card><Card className="p-4"><h3 className="font-semibold">Most picked products</h3><div className="mt-3 space-y-2">{reports.data?.top_products.map((row)=><div key={`${row.name}:${row.currency}`} className="flex justify-between gap-3 border-b border-line pb-2 text-sm"><span>{row.name}<span className="block text-xs text-muted">{row.quantity} units · {row.orders} orders</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card><Card className="p-4 lg:col-span-2"><h3 className="font-semibold">Most active farmers · completed pickups</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{reports.data?.top_farmers.map((row)=><div key={row.id} className="flex justify-between gap-3 border-b border-line pb-2 text-sm"><span>{row.stall_name}<span className="block text-xs text-muted">{row.completed_orders} completed orders</span></span><span className="num">{formatMinor(row.pickup_total_minor,row.currency)}</span></div>)}</div></Card></div></section>
      <section className="mt-8 grid gap-6 lg:grid-cols-2"><div><h2 className="font-display text-2xl font-bold">Account management</h2><input value={accountSearch} onChange={(e)=>setAccountSearch(e.target.value)} placeholder="Search name or phone" className="mt-3 h-10 w-full rounded-xl border border-line bg-elevated px-3 text-sm"/><div className="mt-3 space-y-2">{accounts.data?.map((account)=><Card key={account.id} className="flex items-center justify-between gap-3 p-3"><div><p className="font-medium">{account.full_name} · {account.role}</p><p className="text-xs text-muted">{account.phone}{account.stall_name?` · ${account.stall_name}`:''}</p></div><Button size="sm" variant={account.is_active?'danger':'ghost'} onClick={()=>void accountState(account.id,!account.is_active)}>{account.is_active?'Disable':'Enable'}</Button></Card>)}</div></div><div><h2 className="font-display text-2xl font-bold">Announcements</h2><Card className="mt-3 p-4"><form onSubmit={(e)=>void sendAnnouncement(e)} className="space-y-3"><label className="block text-xs text-muted">Title<input required maxLength={100} value={announcement.title} onChange={(e)=>setAnnouncement({...announcement,title:e.target.value})} className="mt-1 block h-10 w-full rounded-lg border border-line bg-elevated px-3 text-sm text-primary"/></label><label className="block text-xs text-muted">Message<textarea required maxLength={1000} rows={4} value={announcement.body} onChange={(e)=>setAnnouncement({...announcement,body:e.target.value})} className="mt-1 block w-full rounded-lg border border-line bg-elevated p-3 text-sm text-primary"/></label><Button type="submit">Send to active accounts</Button>{announcementMessage?<p role="status" className="text-sm text-accent">{announcementMessage}</p>:null}</form></Card></div></section></> : null}
  </section>;
}
export default function AdminDashboard() { return <RequireAuth roles={['admin']}><Dashboard /></RequireAuth>; }
